
default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: "tech_assignment_dev"

test:
  <<: *default
  database: "tech_assignment_test"

production:
  <<: *default
  database: "tech_assignment_prod"
