<% branch = "#{`git rev-parse --symbolic-full-name --abbrev-ref HEAD --quiet 2>/dev/null`}".strip %>

default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: <%= ["tech_assignment_dev", branch].join("_") %>

test:
  <<: *default
  database: <%= ["tech_assignment_test", branch].join("_") %>

production:
  <<: *default
  database: "tech_assignment_prod"
